#! /bin/sh
### BEGIN INIT INFO
# Provides:          qemu-guest-agent
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: QEMU Guest Agent startup script
# Description:       Start the QEMU Guest Agent if we're running
#                    in a QEMU virtual machine
### END INIT INFO

# Author: Michael Tokarev <mjt@tls.msk.ru>

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="QEMU Guest Agent"
NAME=qemu-ga
DAEMON=/usr/sbin/$NAME
PIDFILE=/var/run/$NAME.pid

# config
DAEMON_ARGS=""
# default transport
TRANSPORT=virtio-serial:/dev/virtio-ports/org.qemu.guest_agent.0

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/qemu-guest-agent ] && . /etc/default/qemu-guest-agent

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that checks whenever system has necessary environment
# It also splits $TRANSPORT into $method and $path
#
do_check_transport() {
	method=${TRANSPORT%%:*}; path=${TRANSPORT#*:}
	case "$method" in
	    virtio-serial | isa-serial)
		if [ ! -e "$path" ]; then
		    log_warning_msg "$NAME: transport endpoint not found, not starting"
		    return 1
		fi
		;;
	esac
}

#
# Function that starts the daemon/service
#
do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
	start-stop-daemon -Sq -p $PIDFILE -x $DAEMON --test > /dev/null \
		|| return 1
	start-stop-daemon -Sq -p $PIDFILE -x $DAEMON -- --daemonize \
		$DAEMON_ARGS -m "$method" -p "$path" \
		|| return 2
}

#
# Function that stops the daemon/service
#
do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred
	start-stop-daemon -Kq --retry=TERM/30/KILL/5 -p $PIDFILE --name $NAME
}

case "$1" in
  start)
	do_check_transport || exit 0
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" $NAME
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" $NAME
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  status)
	status_of_proc "$DAEMON" $NAME && exit 0 || exit $?
	;;
  restart|force-reload)	# we do not support reload
	do_check_transport || exit 0
	log_daemon_msg "Restarting $DESC" $NAME
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
		# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	echo "Usage: /etc/init.d/qemu-guest-agent {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
