build:
	lrelease deepin-wine-packager-en_US.ts -qm deepin-wine-packager-en_US.qm
	lrelease deepin-wine-runner-en_US.ts -qm deepin-wine-runner-en_US.qm
	lrelease installwine-en_US.ts -qm installwine-en_US.qm
	lrelease virtualmachine-en_US.ts -qm virtualmachine-en_US.qm