# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AutoConfig.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchTips = QtWidgets.QLabel(self.centralwidget)
        self.searchTips.setObjectName("searchTips")
        self.horizontalLayout.addWidget(self.searchTips)
        self.searchThings = QtWidgets.QLineEdit(self.centralwidget)
        self.searchThings.setObjectName("searchThings")
        self.horizontalLayout.addWidget(self.searchThings)
        self.saerchBotton = QtWidgets.QPushButton(self.centralwidget)
        self.saerchBotton.setObjectName("saerchBotton")
        self.horizontalLayout.addWidget(self.saerchBotton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.searchList = QtWidgets.QListView(self.centralwidget)
        self.searchList.setObjectName("searchList")
        self.verticalLayout_3.addWidget(self.searchList)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.getInfoButton = QtWidgets.QPushButton(self.centralwidget)
        self.getInfoButton.setObjectName("getInfoButton")
        self.horizontalLayout_2.addWidget(self.getInfoButton)
        self.getFen = QtWidgets.QPushButton(self.centralwidget)
        self.getFen.setObjectName("getFen")
        self.horizontalLayout_2.addWidget(self.getFen)
        self.runBotton = QtWidgets.QPushButton(self.centralwidget)
        self.runBotton.setObjectName("runBotton")
        self.horizontalLayout_2.addWidget(self.runBotton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 36))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.exitProgram = QtWidgets.QAction(MainWindow)
        self.exitProgram.setObjectName("exitProgram")
        self.help = QtWidgets.QAction(MainWindow)
        self.help.setObjectName("help")
        self.openFile = QtWidgets.QAction(MainWindow)
        self.openFile.setObjectName("openFile")
        self.actionGitlink = QtWidgets.QAction(MainWindow)
        self.actionGitlink.setCheckable(True)
        #self.actionGitlink.setChecked(True)
        self.actionGitlink.setObjectName("actionGitlink")
        self.actionGitee = QtWidgets.QAction(MainWindow)
        self.actionGitee.setCheckable(True)
        self.actionGitee.setObjectName("actionGitee")
        self.actionGithub = QtWidgets.QAction(MainWindow)
        self.actionGithub.setCheckable(True)
        self.actionGithub.setChecked(True)
        self.actionGithub.setObjectName("actionGithub")
        self.action_IPv6 = QtWidgets.QAction(MainWindow)
        self.action_IPv6.setCheckable(True)
        self.action_IPv6.setObjectName("action_IPv6")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setCheckable(True)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setCheckable(True)
        self.action_2.setChecked(False)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setCheckable(True)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.openFile)
        self.menu.addSeparator()
        self.menu.addAction(self.exitProgram)
        self.menu_2.addAction(self.actionGitee)
        self.menu_2.addAction(self.actionGithub)
        self.menu_2.addAction(self.actionGitlink)
        
        
        self.menu_2.addAction(self.action_IPv6)
        self.menu_2.addAction(self.action_2)
        self.menu_2.addAction(self.action_3)
        self.menu_2.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "自动部署脚本"))
        self.searchTips.setText(_translate("MainWindow", "搜索内容（为空代表显示所有内容）："))
        self.saerchBotton.setText(_translate("MainWindow", "搜索"))
        self.getInfoButton.setText(_translate("MainWindow", "获取选中项介绍"))
        self.getFen.setText(_translate("MainWindow", "获取/提交选中项的评分和评论"))
        self.runBotton.setText(_translate("MainWindow", "部署此方案"))
        self.menu.setTitle(_translate("MainWindow", "程序"))
        self.menu_2.setTitle(_translate("MainWindow", "切换源"))
        self.about.setText(_translate("MainWindow", "关于"))
        self.exitProgram.setText(_translate("MainWindow", "退出程序"))
        self.help.setText(_translate("MainWindow", "帮助"))
        self.openFile.setText(_translate("MainWindow", "打开本地部署脚本"))
        self.actionGitlink.setText(_translate("MainWindow", "Gitlink 源（推荐）"))
        self.actionGitee.setText(_translate("MainWindow", "Gitee 源"))
        self.actionGithub.setText(_translate("MainWindow", "Github 源（国外用户推荐）"))
        self.action_IPv6.setText(_translate("MainWindow", "备用源1（只限IPv6用户）"))
        self.action.setText(_translate("MainWindow", "本地测试源（127.0.0.1）"))
        self.action_2.setText(_translate("MainWindow", "备用源2"))
        self.action_3.setText(_translate("MainWindow", "备用源3"))

